#database configurations
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/hrms-ats
  config:
    import: env.yaml

#server ports
server:
  port: ${ports.service5}

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://${sr_ip:localhost}:8761/eureka/

#actuator        
management:
  endpoints:
    web:
      exposure:
        include: '*'
