#name of the service
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/hrms-ats
  config:
    import: env.yaml

#server ports
server:
  port: ${ports.service5}

#eureka client config
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

#actuator        
management:
  endpoints:
    web:
      exposure:
        include: '*'
