#database configurations
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver 
    url: jdbc:mysql://localhost:3306/hrms-edms?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&autoReconnect=true
    username: ${mysql.user.name}
    password: ${mysql.user.password}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  config:
    import: env.yaml

#server ports
server:
  port: ${ports.service1}

#eureka client config
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://${sr_ip:localhost}:8761/eureka/

#actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
